This is a two-step challenge and those who complete both the steps will be consider for next round.

You will have a Json file to prepare the dataset which can be downloaded from the link mentioned below.

You need to do a few tasks over the dataset. Task are mentioned below:
JSON parsing with nested columns in a dataframe
Data transformation and aggregations
Validations
Insights

DOWNLOAD THE JSON FILE FORM HERE LINK:
https://drive.google.com/file/d/1_XyMO2udgEwso-oIKdTCxRgg4LWA11o3/view

Use patientDetails and consultationData (medicines) keys from this JSON file.

In [1]:
import pandas as pd
import json
import numpy as np

data = pd.read_json('DataEngineeringQ2.json')

In [2]:
data

,_id,appointmentId,patientDetails,phoneNumber,consultationData
0,T6hf3rb5,40d2-9c9f,"{'_id': 'T6hb630b3', 'firstName': 'Css', 'last...",96686896670,"{'adviceTemplates': [], 'advices': [], 'attach..."
1,T65g3rb5,40dbtc9f,"{'_id': 'T6h33b300', 'firstName': 'Lokesh', 'l...",9496368916,"{'adviceTemplates': [], 'advices': [], 'attach..."
2,T7g6Srb5,g3Wt5c9f,"{'_id': 'TjhB4373', 'phrId': '63b5hvy614d5', '...",7787204833,"{'adviceTemplates': [], 'advices': [], 'attach..."
3,94bg8W8d,fb6-a535,"{'_id': '6df4R5b', 'phrId': '644nig7y', 'first...",9376756879,"{'adviceTemplates': [], 'advices': [], 'attach..."
4,T6h8H56c,67h7KL9,"{'_id': 'lK9hy06a', 'firstName': 'Raghu Viju',...",5267384241,"{'adviceTemplates': [], 'advices': [], 'attach..."
5,T9Jh8c8,Hy7Y91,"{'_id': 'kI9d5c6', 'firstName': 'Dinesh Kumar'...",+919826374025,"{'adviceTemplates': [], 'advices': [], 'attach..."
6,9Is624b9,10dY8a-4a,"{'_id': 'i9R324b7', 'phrId': '67Yt2b97', 'firs...",7587265252,"{'adviceTemplates': [], 'advices': [], 'attach..."
7,T8H9c3c6,e8056Ye8,"{'_id': 'T6h41b5ad3d8002ad9c3c4', 'firstName':...",5586958767,"{'adviceTemplates': [], 'advices': [], 'attach..."
8,T8Ud380,dbc0-c66b,"{'_id': 'T9Iy347e', 'firstName': 'Dinesh', 'la...",9987602525,"{'adviceTemplates': [], 'advices': [], 'attach..."
9,T345fG4,1576a7,"{'_id': 'T4Rb1a2', 'firstName': 'Sanjay', 'las...",9234354366,"{'adviceTemplates': [], 'advices': [], 'attach..."
10,T4F6a175,b6Te4ac,"{'_id': 'Tr4T2173', 'phrId': '6E48U79', 'first...",4863281056,"{'adviceTemplates': [], 'advices': [], 'attach..."
11,TW3r002,bu5Qfb,"{'_id': 'T6Wa50', 'firstName': 'Nirmala', 'las...",8687986800,"{'adviceTemplates': [], 'advices': [], 'attach..."
12,6U6Ra36,86U8Y45,"{'_id': '65sRa36', 'firstName': 'Satish', 'las...",,"{'adviceTemplates': [], 'advices': [], 'attach..."
13,u7Y7Aa5,Ufd7231,"{'_id': 'UG67231', 'phrId': 'T6a7231', 'firstN...",7152684236,"{'labTest': [], 'emrTemplates': [], 'doctorNot..."
14,T3R5dec,E4u5Ea2,"{'_id': 'E4u5Ea2', 'firstName': 'Satyanaaryan'...",,"{'adviceTemplates': [], 'advices': [], 'attach..."
15,T4E7Ge6,T4E3e410,"{'_id': 'T4E7Ge6', 'firstName': 'Nivitha', 'la...",9184723620,"{'adviceTemplates': [], 'advices': [], 'attach..."
16,E5336545,04Re22d,"{'_id': '04Re22d', 'firstName': 'Tejpal', 'las...",,"{'adviceTemplates': [], 'advices': [], 'attach..."
17,T7Ys58b,af9784hf,"{'_id': 'u7dWa589', 'firstName': 'Nandhini', '...",5847346075,"{'adviceTemplates': [], 'advices': [], 'attach..."
18,Y874Us5w,I8eW201,"{'_id': 'TU7e913', 'firstName': 'Dhanamma', 'l...",9064537237,"{'adviceTemplates': [], 'advices': [], 'attach..."
19,Y7s5G42,f7r501cb1,"{'_id': 'H8s2d40', 'firstName': 'Kushal', 'las...",,"{'adviceTemplates': [], 'advices': [], 'attach..."
20,Y7eE5cd8,cf092c8t6c,"{'_id': 'u9cd6', 'phrId': '6463U8s231', 'first...",992727892,"{'adviceTemplates': [], 'advices': [], 'attach..."
21,I9984e8,O02n262e,"{'_id': 'Pdh97S6', 'phrId': 'Jus0480', 'firstN...",6888324121,"{'adviceTemplates': [], 'advices': [], 'attach..."
22,Tu78a783,5dfN9s41,"{'_id': 'h02U8a781', 'firstName': 'Preethi', '...",8248594521,"{'adviceTemplates': [], 'advices': [], 'attach..."
23,U9D2w6c,cc86re0f,"{'_id': 'T6h40a5ad3d8002ad9c06a', 'firstName':...",+917938475936,"{'adviceTemplates': [], 'advices': [], 'attach..."
24,T6hY6sEe,bd99dU7,"{'_id': 'Y7sHec', 'firstName': 'Naresh', 'last...",+9124648979746,"{'adviceTemplates': [], 'advices': [], 'attach..."
25,H7sT6c,bcWe50,"{'_id': 'T6h408981ayf32b63bcfa', 'firstName': ...",+916883788633,"{'adviceTemplates': [], 'advices': [], 'attach..."
26,8Utyd5b,7au8se3,"{'_id': 'T6U67af9', 'firstName': 'Govardhan', ...",+916636278363,"{'adviceTemplates': [], 'advices': [], 'attach..."
27,y87Ta5c7,432cT213,"{'_id': 'R53Et5W', 'firstName': 'Rajeshwari', ...",6525356535,"{'adviceTemplates': [], 'advices': [], 'attach..."
28,Ub7S65b7,D3fFr42c,"{'_id': 'dE3r$2b5', 'firstName': 'Santosh', 'l...",,"{'adviceTemplates': [], 'advices': [], 'attach..."
29,yD7s2d7,7uyT6Rs,"{'_id': 'TI93Hd5', 'firstName': 'Tarachand', '...",+919093872282,"{'adviceTemplates': [], 'advices': [], 'attach..."
30,I9Sb4e8,O02n2e,"{'_id': 'Pdh97S6', 'phrId': 'Jus0480', 'firstN...",+916888324121,"{'adviceTemplates': [], 'advices': [], 'attach..."

In [3]:
data['patientDetails']

0     {'_id': 'T6hb630b3', 'firstName': 'Css', 'last...
1     {'_id': 'T6h33b300', 'firstName': 'Lokesh', 'l...
2     {'_id': 'TjhB4373', 'phrId': '63b5hvy614d5', '...
3     {'_id': '6df4R5b', 'phrId': '644nig7y', 'first...
4     {'_id': 'lK9hy06a', 'firstName': 'Raghu Viju',...
5     {'_id': 'kI9d5c6', 'firstName': 'Dinesh Kumar'...
6     {'_id': 'i9R324b7', 'phrId': '67Yt2b97', 'firs...
7     {'_id': 'T6h41b5ad3d8002ad9c3c4', 'firstName':...
8     {'_id': 'T9Iy347e', 'firstName': 'Dinesh', 'la...
9     {'_id': 'T4Rb1a2', 'firstName': 'Sanjay', 'las...
10    {'_id': 'Tr4T2173', 'phrId': '6E48U79', 'first...
11    {'_id': 'T6Wa50', 'firstName': 'Nirmala', 'las...
12    {'_id': '65sRa36', 'firstName': 'Satish', 'las...
13    {'_id': 'UG67231', 'phrId': 'T6a7231', 'firstN...
14    {'_id': 'E4u5Ea2', 'firstName': 'Satyanaaryan'...
15    {'_id': 'T4E7Ge6', 'firstName': 'Nivitha', 'la...
16    {'_id': '04Re22d', 'firstName': 'Tejpal', 'las...
17    {'_id': 'u7dWa589', 'firstName': 'Nandhini', '...
18    {'_id': 'TU7e913', 'firstName': 'Dhanamma', 'l...
19    {'_id': 'H8s2d40', 'firstName': 'Kushal', 'las...
20    {'_id': 'u9cd6', 'phrId': '6463U8s231', 'first...
21    {'_id': 'Pdh97S6', 'phrId': 'Jus0480', 'firstN...
22    {'_id': 'h02U8a781', 'firstName': 'Preethi', '...
23    {'_id': 'T6h40a5ad3d8002ad9c06a', 'firstName':...
24    {'_id': 'Y7sHec', 'firstName': 'Naresh', 'last...
25    {'_id': 'T6h408981ayf32b63bcfa', 'firstName': ...
26    {'_id': 'T6U67af9', 'firstName': 'Govardhan', ...
27    {'_id': 'R53Et5W', 'firstName': 'Rajeshwari', ...
28    {'_id': 'dE3r$2b5', 'firstName': 'Santosh', 'l...
29    {'_id': 'TI93Hd5', 'firstName': 'Tarachand', '...
30    {'_id': 'Pdh97S6', 'phrId': 'Jus0480', 'firstN...
Name: patientDetails, dtype: object

In [4]:
data_ = pd.json_normalize(data['patientDetails'])

In [29]:
data_2 = pd.json_normalize(data['consultationData'])

In [5]:
data_

,_id,firstName,lastName,emailId,gender,alternateContact,birthDate,phrId,customId,chat._id,chat.channelId
0,T6hb630b3,Css,,,,,None,NaN,NaN,NaN,NaN
1,T6h33b300,Lokesh,,,M,NaN,1996-05-16T18:30:00.000Z,NaN,NaN,NaN,NaN
2,TjhB4373,Shila,Das,,NaN,NaN,NaN,63b5hvy614d5,NaN,NaN,NaN
3,6df4R5b,Bhavika,Ben Panchal,,F,NaN,1988-04-24T14:30:00.000Z,644nig7y,NaN,NaN,NaN
4,lK9hy06a,Raghu Viju,,,NaN,,NaN,NaN,NaN,NaN,NaN
5,kI9d5c6,Dinesh Kumar,,,M,NaN,1983-05-16T18:30:00.000Z,NaN,3FPEUCW8HACJ,09hUb5c7,NaN
6,i9R324b7,Lalit,Sankhwal,,M,,2003-06-27T14:30:00.000Z,67Yt2b97,NaN,NaN,NaN
7,T6h41b5ad3d8002ad9c3c4,Ravi,,,NaN,NaN,NaN,NaN,8AV4ICI5I389,T6h41b5ad3d8002ad9c3c5,NaN
8,T9Iy347e,Dinesh,,,M,NaN,1983-05-16T18:30:00.000Z,NaN,0308MSAHYR8K,T9IsT37f,NaN
9,T4Rb1a2,Sanjay,,,M,NaN,1998-05-16T18:30:00.000Z,NaN,8S7A3D4K4WZH,7Yd9b1a3,NaN
10,Tr4T2173,Akshay,Akshay,,M,NaN,1988-04-08T00:00:00.000Z,6E48U79,83AH0K04SSTV,Tr4W174,9IrR9ce7
11,T6Wa50,Nirmala,,,F,NaN,1971-05-16T18:30:00.000Z,NaN,832ZIS6ZCAHH,T6h3635ad3d8002ad9b001,NaN
12,65sRa36,Satish,,,NaN,NaN,1970-05-16T18:30:00.000Z,NaN,YW883CARSES3,6Y6a36,NaN
13,UG67231,Kalaiarasi,Kalaiarasi,,F,,1997-07-31T00:00:00.000Z,T6a7231,NaN,NaN,NaN
14,E4u5Ea2,Satyanaaryan,,,NaN,,NaN,NaN,E4u5Ea2,E4u5Ea2,NaN
15,T4E7Ge6,Nivitha,,,F,NaN,1997-05-16T18:30:00.000Z,NaN,NaN,NaN,NaN
16,04Re22d,Tejpal,,,M,NaN,1972-05-16T18:30:00.000Z,NaN,04Re22d,04Re22d,NaN
17,u7dWa589,Nandhini,,,F,NaN,2001-05-16T18:30:00.000Z,NaN,NaN,NaN,NaN
18,TU7e913,Dhanamma,,,F,NaN,NaN,NaN,y7ewr5w,u8e6fgd14,NaN
19,H8s2d40,Kushal,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,u9cd6,Daniya,Zehra,,F,NaN,2001-08-27T00:00:00.000Z,6463U8s231,NaN,NaN,NaN
21,Pdh97S6,Jay,Sharma,,M,NaN,1998-11-19T23:30:00.000Z,Jus0480,NaN,NaN,NaN
22,h02U8a781,Preethi,,,F,NaN,1996-05-16T18:30:00.000Z,NaN,H8NdI3MAW,T6h9a782,NaN
23,T6h40a5ad3d8002ad9c06a,VITTHAL SHANKARRAO GHATE,,NaN,NaN,+917797689682,NaN,NaN,83AAWWI24W63,T6h40a1becc5002908b235,NaN
24,Y7sHec,Naresh,,,M,NaN,1992-05-16T18:30:00.000Z,NaN,NaN,NaN,NaN
25,T6h408981ayf32b63bcfa,Suresh,Gaikwad,,NaN,,NaN,NaN,ABCD1419,Hsb690S,NaN
26,T6U67af9,Govardhan,,,NaN,,NaN,NaN,Gya7sfw,u7sg9be5a,NaN
27,R53Et5W,Rajeshwari,,,F,NaN,1999-05-16T18:30:00.000Z,NaN,K44RwH0T,T6h2fT5535c6,NaN
28,dE3r$2b5,Santosh,,,F,NaN,1972-05-16T18:30:00.000Z,NaN,NaN,NaN,NaN
29,TI93Hd5,Tarachand,,,M,,1980-03-22T18:30:00.000Z,NaN,90hjdX2,TH8W2d6,NaN
30,Pdh97S6,Jay,Sharma,,M,NaN,1991-11-19T23:30:00.000Z,Jus0480,NaN,NaN,NaN

In [30]:
data_2.head()

,adviceTemplates,advices,attachments,chiefComplaints,customOne,customThree,customTwo,disease,doctorNotes,emergencyInstructions,...,labTest,languageCode,medicineTemplates,medicines,procedures,prognosis,sharePrescription,_id,updatedAt,createdAt
0,[],[],[],[],[],[],[],[],,[],...,[],en,[],"[{'medicineId': '619404', 'medicineName': 'A',...",[],[],False,NaN,NaN,NaN
1,[],[],[],[],[],[],[],[],,[],...,[],en,[],"[{'medicineId': '619404', 'medicineName': 'A',...",[],[],False,NaN,NaN,NaN
2,[],[],[],[],[],[],[],[],,[],...,[],en,[],"[{'medicineId': '619404', 'medicineName': 'B',...",[],[],False,NaN,NaN,NaN
3,[],[],[],[],[],[],[],[],,[],...,[],en,[],"[{'medicineId': '619704', 'medicineName': 'B',...",[],[],False,NaN,NaN,NaN
4,[],[],[],[],[],[],[],[],,[],...,[],en,[],"[{'medicineId': '619384', 'medicineName': 'D',...",[],[],False,NaN,NaN,NaN

In [6]:
data_.describe()

,_id,firstName,lastName,emailId,gender,alternateContact,birthDate,phrId,customId,chat._id,chat.channelId
count,31,31,31,30,22,9,21,8,16,16,1
unique,30,30,9,1,3,2,18,7,16,16,1
top,Pdh97S6,Jay,,,M,,1996-05-16T18:30:00.000Z,Jus0480,3FPEUCW8HACJ,09hUb5c7,9IrR9ce7
freq,2,2,22,30,11,8,2,2,1,1,1

In [7]:
data_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               31 non-null     object
 1   firstName         31 non-null     object
 2   lastName          31 non-null     object
 3   emailId           30 non-null     object
 4   gender            22 non-null     object
 5   alternateContact  9 non-null      object
 6   birthDate         21 non-null     object
 7   phrId             8 non-null      object
 8   customId          16 non-null     object
 9   chat._id          16 non-null     object
 10  chat.channelId    1 non-null      object
dtypes: object(11)
memory usage: 2.8+ KB

## 1
Share percentage of missing values, for the columns firstName, lastName and DOB from patientDetails.

Note: Missing values are defined as blank and empty strings. Percentage rounded off to 2 decimal

In [8]:
## 1
## Share percentage of missing values, for the columns firstName, lastName and DOB from patientDetails.

## Note: Missing values are defined as blank and empty strings. Percentage rounded off to 2 decimal

In [9]:
# Replace blank and empty strings with NaN
data_ = data_.replace(r'^\s*$', np.nan, regex=True)

In [13]:
data_.head()

,_id,firstName,lastName,emailId,gender,alternateContact,birthDate,phrId,customId,chat._id,chat.channelId
0,T6hb630b3,Css,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
1,T6h33b300,Lokesh,NaN,NaN,M,NaN,1996-05-16T18:30:00.000Z,NaN,NaN,NaN,NaN
2,TjhB4373,Shila,Das,NaN,NaN,NaN,NaN,63b5hvy614d5,NaN,NaN,NaN
3,6df4R5b,Bhavika,Ben Panchal,NaN,F,NaN,1988-04-24T14:30:00.000Z,644nig7y,NaN,NaN,NaN
4,lK9hy06a,Raghu Viju,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
total_nums = len(data_['_id'])
total_nums

31

In [20]:
firstName_null = data_['firstName'].isnull().sum()

In [21]:
#  percentage
firstName_null/total_nums *100

0.0

In [23]:
lastName_null = data_['lastName'].isnull().sum()

In [24]:
#  percentage
lastName_null/total_nums *100

70.96774193548387

In [26]:
birthDate_null = data_['birthDate'].isnull().sum()

In [27]:
#  percentage
birthDate_null/total_nums *100

32.25806451612903

What is the percentage of female gender after imputation of gender column basis mode.
(1 Point)

In [28]:
data_['gender'].head()

0     NaN
1       M
2     NaN
3       F
4     NaN
5       M
6       M
7     NaN
8       M
9       M
10      M
11      F
12    NaN
13      F
14    NaN
15      F
16      M
17      F
18      F
19    NaN
20      F
21      M
22      F
23    NaN
24      M
25    NaN
26    NaN
27      F
28      F
29      M
30      M
Name: gender, dtype: object

In [80]:
data_['gender'].mode()

0    M
Name: gender, dtype: object

In [81]:
Counter(data_['gender'])

Counter({nan: 10, 'M': 11, 'F': 10})

What is the percentage of female gender after imputation of gender column basis mode.
(1 Point)

In [82]:
10 / 21

0.47619047619047616

Add a column ageGroup that categorizes patients into age groups (e.g., Child for ages 0-12, Teen for ages 13-19, Adult for ages 20-59, Senior for ages 60+).

What is count of Adult?

In [84]:
data_['birthDate'].dtype()

0                         None
1     1996-05-16T18:30:00.000Z
2                          NaN
3     1988-04-24T14:30:00.000Z
4                          NaN
5     1983-05-16T18:30:00.000Z
6     2003-06-27T14:30:00.000Z
7                          NaN
8     1983-05-16T18:30:00.000Z
9     1998-05-16T18:30:00.000Z
10    1988-04-08T00:00:00.000Z
11    1971-05-16T18:30:00.000Z
12    1970-05-16T18:30:00.000Z
13    1997-07-31T00:00:00.000Z
14                         NaN
15    1997-05-16T18:30:00.000Z
16    1972-05-16T18:30:00.000Z
17    2001-05-16T18:30:00.000Z
18                         NaN
19                         NaN
20    2001-08-27T00:00:00.000Z
21    1998-11-19T23:30:00.000Z
22    1996-05-16T18:30:00.000Z
23                         NaN
24    1992-05-16T18:30:00.000Z
25                         NaN
26                         NaN
27    1999-05-16T18:30:00.000Z
28    1972-05-16T18:30:00.000Z
29    1980-03-22T18:30:00.000Z
30    1991-11-19T23:30:00.000Z
Name: birthDate, dtype: object

In [91]:
pd.to_datetime('today')

Timestamp('2024-07-19 05:17:16.355260')

In [92]:
data_date = data_.dropna(subset=['birthDate'])

In [93]:
data_date['birthDate'] = pd.to_datetime(data_date['birthDate'])
data_date['birthDate']

data_date['age'] = (pd.to_datetime('today') - data_date['birthDate'])

data_date['ageGroup'] = pd.cut(data_date['age'], bins=[0, 12, 19, 59, 120], labels=['Child', 'Teen', 'Adult', 'Senior'])

<ipython-input-93-d56051592cf2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_date['birthDate'] = pd.to_datetime(data_date['birthDate'])

TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects

In [ ]:
  # Add a column ageGroup that categorizes patients into age groups (e.g., Child for ages 0-12, Teen for ages 13-19, Adult for ages 20-59, Senior for ages 60+).

# What is count of Adult?

In [32]:
# Calculate the average number of medicines prescribed in the dataset.

data_2['medicines'].head()

0    [{'medicineId': '619404', 'medicineName': 'A',...
1    [{'medicineId': '619404', 'medicineName': 'A',...
2    [{'medicineId': '619404', 'medicineName': 'B',...
3    [{'medicineId': '619704', 'medicineName': 'B',...
4    [{'medicineId': '619384', 'medicineName': 'D',...
Name: medicines, dtype: object

In [35]:
f  = lambda x : len(x)

In [38]:
data_try = data_2.copy()

In [39]:
data_try["medicines"].apply(f)

0     2
1     2
2     3
3     1
4     2
5     4
6     2
7     1
8     1
9     0
10    1
11    3
12    0
13    3
14    0
15    3
16    2
17    3
18    4
19    0
20    1
21    3
22    4
23    3
24    0
25    4
26    2
27    4
28    0
29    4
30    4
Name: medicines, dtype: int64

In [46]:
sum(data_try["medicines"].apply(f)) / 30

2.2

In [47]:
data_try["medicines"]

0     [{'medicineId': '619404', 'medicineName': 'A',...
1     [{'medicineId': '619404', 'medicineName': 'A',...
2     [{'medicineId': '619404', 'medicineName': 'B',...
3     [{'medicineId': '619704', 'medicineName': 'B',...
4     [{'medicineId': '619384', 'medicineName': 'D',...
5     [{'medicineId': '643404', 'medicineName': 'A',...
6     [{'medicineId': '632304', 'medicineName': 'D',...
7     [{'medicineId': '619404', 'medicineName': 'A',...
8     [{'medicineId': '619504', 'medicineName': 'E',...
9                                                    []
10    [{'medicineId': '619504', 'medicineName': 'E',...
11    [{'medicineId': '619504', 'medicineName': 'E',...
12                                                   []
13    [{'medicineId': '619504', 'medicineName': 'A',...
14                                                   []
15    [{'medicineId': '619504', 'medicineName': 'B',...
16    [{'medicineId': '619504', 'medicineName': 'C',...
17    [{'medicineId': '619504', 'medicineName': 'A',...
18    [{'medicineId': '619504', 'medicineName': 'A',...
19                                                   []
20    [{'medicineId': '619504', 'medicineName': 'D',...
21    [{'medicineId': '612504', 'medicineName': 'D',...
22    [{'medicineId': '611504', 'medicineName': 'A',...
23    [{'medicineId': '612504', 'medicineName': 'A',...
24                                                   []
25    [{'medicineId': '612504', 'medicineName': 'D',...
26    [{'medicineId': '612504', 'medicineName': 'C',...
27    [{'medicineId': '612504', 'medicineName': 'A',...
28                                                   []
29    [{'medicineId': '612504', 'medicineName': 'A',...
30    [{'medicineId': '612504', 'medicineName': 'A',...
Name: medicines, dtype: object

In [66]:
data_try["medicines"][0]

[{'medicineId': '619404',
  'medicineName': 'A',
  'medicineNameStrengthType': '',
  'frequency': '1-0-1',
  'duration': '90',
  'durationIn': 'DAYS',
  'instruction': 'AFTER MEAL',
  'isActive': True},
 {'medicineId': '619804',
  'medicineName': 'B',
  'medicineNameStrengthType': '',
  'frequency': '1-0-1',
  'duration': '90',
  'durationIn': 'DAYS',
  'instruction': 'AFTER MEAL',
  'isActive': False}]

In [51]:
data_try["medicines"][0][0]["medicineName"]

'A'

In [61]:
meds = []
for i in data_try["medicines"] :
  for j in i:
    med = j["medicineName"]
    meds.append(med)

In [62]:
meds

['A',
 'B',
 'A',
 'C',
 'B',
 'A',
 'C',
 'B',
 'D',
 'A',
 'A',
 'D',
 'E',
 'C',
 'D',
 'E',
 'A',
 'E',
 'E',
 'E',
 'A',
 'D',
 'A',
 'B',
 'D',
 'B',
 'D',
 'C',
 'C',
 'A',
 'A',
 'C',
 'B',
 'A',
 'B',
 'C',
 'D',
 'D',
 'D',
 'D',
 'B',
 'A',
 'G',
 'B',
 'D',
 'A',
 'B',
 'C',
 'D',
 'A',
 'E',
 'C',
 'C',
 'D',
 'A',
 'C',
 'C',
 'D',
 'A',
 'B',
 'C',
 'D',
 'A',
 'D',
 'D',
 'B']

In [63]:
from  collections import Counter
Counter(meds)

Counter({'A': 17, 'B': 12, 'C': 13, 'D': 17, 'E': 6, 'G': 1})

In [64]:
l = Counter(meds)

In [65]:
sorted(l)

['A', 'B', 'C', 'D', 'E', 'G']

In [68]:
meds_a = []
for i in data_try["medicines"] :
  for j in i:
    med = j["isActive"]
    meds_a.append(med)

In [69]:
meds_a

[True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True]

In [70]:
l_a = Counter(meds)

In [73]:
a = dict(l_a)
a

{True: 46, False: 20}

In [76]:
# percentages
active = a[True]
non_active = a[False]
active , non_active

(46, 20)

In [78]:
active / (active + non_active) , non_active / (active + non_active)

(0.696969696969697, 0.30303030303030304)

In [ ]:
# Add a column isValidMobile of boolean which contains the values true or false against each value from phoneNumber column If a phone number is a valid Indian phone number.

# CREATE YOUR OWN LOGIC, DON’T USE ANY EXTERNAL PYTHON LIBRARY FOR VALIDATION
#
# true : indicates number is valid
# false : indicates number is not valid

# Problem Statement: Design a logic to check whether a phone number is valid or not.

# General rules to check:
# A valid number can have '+91' or '91' as prefix, a valid number must lie be between 6000000000-9999999999

# Example:
# +919876787687 is valid
# 919877475896 is valid
# +913454768688 is invalid
# 9876787687 is valid
# 3454768688 is invalid
# 57769666 is invalid

# Return the number of valid phone numbers found in the dataset.

In [97]:
import pandas as pd

def validate_phone(phone):
    return ('91' in phone and 6000000000 <= int(phone[2:]) <= 9999999999) or ('+91' in phone and 6000000000 <= int(phone[2:]) <= 9999999999)

data['isValidMobile'] = data['phoneNumber'].apply(validate_phone)

In [98]:
data['phoneNumber']

0        96686896670
1         9496368916
2         7787204833
3         9376756879
4         5267384241
5      +919826374025
6         7587265252
7         5586958767
8         9987602525
9         9234354366
10        4863281056
11        8687986800
12
13        7152684236
14
15        9184723620
16
17        5847346075
18        9064537237
19
20         992727892
21        6888324121
22        8248594521
23     +917938475936
24    +9124648979746
25     +916883788633
26     +916636278363
27        6525356535
28
29     +919093872282
30     +916888324121
Name: phoneNumber, dtype: object

In [99]:
data['isValidMobile']

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
Name: isValidMobile, dtype: bool

In [ ]:
import pandas as pd

correlation = data_try["medicines"].apply(f).corr(date['age'])
rounded_correlation = round(correlation, 2)

print(rounded_correlation)